<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FileCabinet.Domain\FileCabinet.Domain.csproj" />
    <ProjectReference Include="..\FileCabinet.Infrastructure\FileCabinet.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>data\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>
</Project>
