CREATE TABLE [dbo].[Address]
(
    [Id] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_Address] PRIMARY KEY,
    [Street] NVARCHAR(50) NOT NULL,
    [City] NVARCHAR(20) NULL,
    [State] NVARCHAR(50) NULL,
    [ZipCode] NVARCHAR(50) NULL
);